
auth.token=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

defaults.org=internal-developer-platform
defaults.project=stitching

defaults.url=https://sentry.io/
